# Generated by Django 5.0.7 on 2024-07-24 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_datedcompleted_task_datecompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='important',
        ),
    ]
